apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: strimzi-drain-cleaner
  labels:
    app: strimzi-drain-cleaner
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true
webhooks:
  - name: strimzi-drain-cleaner.strimzi.io
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods/eviction"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "strimzi-operator"
        name: "strimzi-drain-cleaner"
        path: /drainer
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5
