apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: amq-streams-infra
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/skodjob/deployment-hub
              revision: HEAD
              files:
                - path: "amq-streams/**/argo-config.yaml"
          - clusters:
              selector:
                matchLabels:
                  environment: 'downstream'
  template:
    metadata:
      name: '{{appname}}-{{name}}'
      labels:
        project: skodjob
        app: strimzi
    spec:
      project: strimzi
      source:
        repoURL: https://github.com/skodjob/deployment-hub
        targetRevision: HEAD
        path: '{{source}}'
        directory:
          recurse: true
          exclude: '{argo-config.yaml}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            project: skodjob
            strimzi.io/sync-secrets: "true"
      destination:
        name: '{{name}}'
        namespace: '{{namespace}}'
