apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: streams
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: streams/**/argo-config.yaml
              repoURL: 'https://github.com/skodjob/deployment-hub'
              revision: HEAD
          - clusters:
              selector:
                matchLabels:
                  environment: upstream
  template:
    metadata:
      name: '{% raw %}{{appname}}-{{name}}{% endraw %}'
      labels:
        project: skodjob
        app: streams
    spec:
      project: streams
      source:
        repoURL: https://github.com/skodjob/deployment-hub
        targetRevision: HEAD
        path: '{% raw %}{{source}}{% endraw %}'
        kustomize:
          patches:
            - target:
                kind: Console
                name: streams-console
              patch: |-
                - op: replace
                  path: "/spec/hostname"
                  value: "{% raw %}{{namespace}}-{{namespace}}.apps.{{name}}{% endraw %}.{{ cluster_domain }}"
                - op: replace
                  path: "/spec/security/oidc/authServerUrl"
                  value: "{% raw %}https://streams-dex-streams-dex.apps.{{name}}{% endraw %}.{{ cluster_domain }}"
            - target:
                kind: Secret
                name: keystore-password
              patch: |-
                - op: replace
                  path: "/stringData/keystore.password"
                  value: "{{ kroxy_keystore_password }}"
            - target:
                kind: Secret
                name: vault-token
              patch: |-
                - op: replace
                  path: "/stringData/token"
                  value: "{{ vault_kroxy_token }}"
            # Clients
            - target:
                kind: Deployment
                name: consumer
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/2/value"
                  value: "https://skodjob-keycloak-ingress-skodjob-keycloak.apps.skodjob-infra.{{ cluster_domain }}/realms/{{ rhbk_realm_name }}/protocol/openid-connect/token"
            - target:
                kind: Deployment
                name: consumer-direct
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/2/value"
                  value: "https://skodjob-keycloak-ingress-skodjob-keycloak.apps.skodjob-infra.{{ cluster_domain }}/realms/{{ rhbk_realm_name }}/protocol/openid-connect/token"
            - target:
                kind: Deployment
                name: producer
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/2/value"
                  value: "https://skodjob-keycloak-ingress-skodjob-keycloak.apps.skodjob-infra.{{ cluster_domain }}/realms/{{ rhbk_realm_name }}/protocol/openid-connect/token"
            - target:
                kind: Deployment
                name: producer-invalid
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/2/value"
                  value: "https://skodjob-keycloak-ingress-skodjob-keycloak.apps.skodjob-infra.{{ cluster_domain }}/realms/{{ rhbk_realm_name }}/protocol/openid-connect/token"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            project: skodjob
            app: streams
            strimzi.io/sync-secrets: "{% raw %}{{namespace}}{% endraw %}"
      destination:
        name: '{% raw %}{{name}}{% endraw %}'
        namespace: '{% raw %}{{namespace}}{% endraw %}'
