apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: strimzi-infra
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - git:
              files:
                - path: strimzi/**/argo-config.yaml
              repoURL: 'https://github.com/skodjob/deployment-hub'
              revision: HEAD
          - clusters:
              selector:
                matchLabels:
                  environment: upstream
    - matrix:
        generators:
          - git:
              files:
                - path: infra/strimzi/argo-config.yaml
              repoURL: 'https://github.com/skodjob/deployment-hub'
              revision: HEAD
          - clusters:
              selector:
                matchLabels:
                  environment: upstream
  template:
    metadata:
      name: '{{appname}}-{{name}}'
      labels:
        project: skodjob
        app: strimzi
    spec:
      project: strimzi
      source:
        repoURL: https://github.com/skodjob/deployment-hub
        targetRevision: HEAD
        path: '{{source}}'
        directory:
          recurse: true
          exclude: '{argo-config.yaml}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            project: skodjob
            app: strimzi
            strimzi.io/sync-secrets: "true"
      destination:
        name: '{{name}}'
        namespace: '{{namespace}}'
