---
- name: Create Loki datasources on Infra cluster
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_logging_namespace }}"
    apply: true
    definition:
      apiVersion: integreatly.org/v1alpha1
      kind: GrafanaDataSource
      metadata:
        name: "loki-{{ clusterName }}-{{ loki_tenant_id }}"
        namespace: "{{ infra_monitoring_namespace }}"
        labels:
          project: "tealc"
          managed: "true"
      spec:
        name: "loki-{{ clusterName }}-{{ loki_tenant_id }}"
        datasources:
          - access: proxy
            type: loki
            url: "https://{{ loki_gateway_route_url }}:443/api/logs/v1/{{ loki_tenant_id }}"
            editable: true
            jsonData:
              httpHeaderName1: X-Scope-OrgID
              httpHeaderName2: Authorization
              tlsAuthWithCACert: true
            name: "Loki-{{ clusterName }}-{{ loki_tenant_id }}"
            secureJsonData:
              httpHeaderValue1: "{{ loki_tenant_id }}"
              httpHeaderValue2: "Bearer {{ loki_gateway_token }}"
              tlsCACert: "{{ loki_gateway_ca_cert }}"
  vars:
    loki_gateway_token: "null"
    loki_gateway_route_url: "null"
    loki_tenant_id: "null"
    loki_gateway_ca_cert: "null"
  loop:
    - "application"
    - "audit"
    - "infrastructure"
  loop_control:
    loop_var: tenant_id
