apiVersion: v1
kind: ServiceAccount
metadata:
  name: streams-dex
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://{{ streams_dex_namespace }}-{{ streams_dex_namespace }}.apps.{{ cluster_name }}.{{ cluster_domain }}/callback
