---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: streams-dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: streams-dex
subjects:
- kind: ServiceAccount
  name: streams-dex        # Service account assigned to the dex pod
  namespace: streams-dex   # The namespace dex is running in
