---
kind: Secret
apiVersion: v1
metadata:
  name: streams-dex
stringData:
  DEX_CLIENT_ID: "{{ streams_console_id }}"
  DEX_CLIENT_SECRET: "{{ streams_console_secret }}"
  config.yaml: |
    issuer: https://{{ streams_dex_namespace }}-{{ streams_dex_namespace }}.apps.{{ cluster_name }}.{{ cluster_domain }}

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      http: 0.0.0.0:5556
      allowedOrigins: ['*']

    oauth2:
      skipApprovalScreen: true

    staticClients:
      # This is the OIDC client ID in plaintext
      - id: {{ streams_console_id }}
        name: Streams Console
        redirectURIs:
          - https://{{ streams_console_namespace }}-{{ streams_console_namespace }}.apps.{{ cluster_name }}.{{ cluster_domain }}/api/auth/callback/oidc
        secret: {{ streams_console_secret }}


    connectors:
    - type: openshift
      id: openshift
      name: OpenShift
      config:
        issuer: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
        # OpenShift root CA
        rootCA: /etc/ssl/openshift.pem
        # Communicate to OpenShift without validating SSL certificates
        insecureCA: false

        # Credentials can be string literals or pulled from the environment.
        clientID: streams-console
        clientSecret: {{ streams_console_secret }}

        # Optional list of required groups a user must be a member of
        groups: []

        # Redirect to the console's callback following authentication
        redirectURI: https://{{ streams_dex_namespace }}-{{ streams_dex_namespace }}.apps.{{ cluster_name }}.{{ cluster_domain }}/callback
        userGroupsKey: "groups"  # Ensure this is set


