---
kind: Secret
apiVersion: v1
metadata:
  name: streams-console-oidc
  labels:
    project: skodjob
    type: streams-console-secret
  annotations:
    replicator.v1.mittwald.de/replicate-to: "{{ streams_console_namespace }}"
stringData:
  clientId: "{{ streams_console_id }}"
  clientSecret: "{{ streams_console_secret }}"
