---
apiVersion: v1
kind: Service
metadata:
  name: streams-dex
spec:
  type: ClusterIP
  ports:
    - name: dex
      port: 5556
      protocol: TCP
      targetPort: http
  selector:
    app: streams-dex
