---
# clusters connections
- import_tasks: common/check_parameters.yaml
  tags: [always, check-params]

- import_tasks: common/check_clients.yaml
  tags: [always, check-clients]

- import_tasks: common/set_facts.yaml
  tags: [always]

- import_tasks: common/prepare_kubeconfigs.yaml
  tags: [always, kubeconfigs]

# infra installation
# Install ACM
- import_tasks: infra-setup/install/advanced-cluster-management/install_acm.yaml
  tags: [never, infra, clusters, acm]
# Create clusters if they don't exist
- import_tasks: infra-setup/install/create_clusters_hive.yaml
  tags: [never, infra, clusters, hive]

- import_tasks: common/set_facts.yaml
  tags: [infra]

- import_tasks: common/prepare_kubeconfigs.yaml
  tags: [infra, kubeconfigs]

- include_tasks:
    file: infra-setup/install/hive/create-htpasswd.yaml
    apply:
      tags: [htpasswd, infra, never]
  tags: [htpasswd, infra, never]
  loop: "{{ clusters }}"
  loop_control:
    loop_var: cluster_name

# Create all secrets related to cluster connections
- include_tasks:
    file: infra-setup/prepare_access.yaml
    apply:
      tags: [setup-workers-access, infra, never]
  tags: [setup-workers-access, infra, never]
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: worker

- include_tasks:
    file: infra-setup/install/advanced-cluster-management/register_clusters.yaml
    apply:
      tags: [clusters, infra, never]
  tags: [clusters, infra, never]
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: cluster

# Configure the clusters
- import_tasks: infra-setup/configure_infra_cluster.yaml
  tags: [machine-sets, chrony, infra, never]

- include_tasks:
    file: infra-setup/configure_worker_cluster.yaml
    apply:
      tags: [machine-sets, chrony, infra, never]
  tags: [machine-sets, chrony, infra, never]
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: worker

- include_tasks:
    file: infra-setup/install/advanced-cluster-management/install_observability.yaml
    apply:
      tags: [acm, logging, infra, monitoring, never]
  tags: [acm, logging, infra, monitoring, never]

- import_tasks: infra-setup/install/install_tekton.yaml
  tags: [tekton, infra, never]

- import_tasks: infra-setup/install/install_argo.yaml
  tags: [argo, infra, never]

- import_tasks: monitoring/install_monitoring.yaml
  tags: [monitoring, grafana, infra, never]

- import_tasks: infra-setup/install/install_kubernetes-replicator.yaml
  tags: [kubernetes-replicator, infra, never]

- import_tasks: infra-setup/install/orchestrate_cert_manager.yaml
  tags: [cert-manager, cm, infra, never]

- import_tasks: infra-setup/install/orchestrate_logging.yaml
  tags: [logging, infra, monitoring, never]

- import_tasks: infra-setup/install/orchestrate_acs.yaml
  tags: [acs, infra, security, never]

- import_tasks: infra-setup/install/install_argo_workflow.yaml
  tags: [infra, ci, workflow]

- import_tasks: infra-setup/install/install_links.yaml
  tags: [infra, console-link, links, never]

# Scenarios - Has to be migrated to the new format!!!
- import_tasks: scenario-deployment/infra/argo-deploy-strimzi-infra.yaml
  tags: [argo-apps, argo-strimzi-infra, strimzi-infra, never]

- import_tasks: scenario-deployment/infra/argo-deploy-amq-streams-infra.yaml
  tags: [argo-apps, argo-strimzi-infra, strimzi-infra, never]

- import_tasks: scenario-deployment/debezium/argo-deploy-debezium.yaml
  tags: [argo-apps, argo-strimzi-infra, strimzi-infra, never]

- import_tasks: scenario-deployment/monitoring/argo-deploy-strimzi-monitoring.yaml
  tags: [argo-apps, argo-strimzi-monitoring, strimzi-infra, never]

- import_tasks: scenario-deployment/open-data-hub/argo-deploy-odh.yaml
  tags: [argo-apps, argo-odh, odh, never]

- import_tasks: scenario-deployment/tekton/infra-tkn-pipelines.yaml
  tags: [d, infra, never]

- import_tasks: scenario-deployment/tekton/strimzi-tkn-pipelines.yaml
  tags: [tekton-pipelines, strimzi-infra, never]

- import_tasks: scenario-deployment/tekton/odh-tkn-pipelines.yaml
  tags: [tekton-pipelines, odh, never]

- import_tasks: scenario-deployment/tekton/chaos-tkn-pipelines.yaml
  tags: [tekton-pipelines, chaos, never]

# Teardown
- import_tasks: infra-setup/delete/delete_argo.yaml
  tags: [never, teardown, teardown-argo]

- import_tasks: infra-setup/delete/delete_tekton.yaml
  tags: [never, teardown, teardown-tekton]

- import_tasks: monitoring/delete_monitoring.yaml
  tags: [never, teardown, teardown-monitoring]

- import_tasks: infra-setup/delete/delete_logging.yaml
  tags: [never, teardown-logging, teardown, teardown-monitoring]

- import_tasks: infra-setup/delete/delete_links.yaml
  tags: [never, teardown, teardown-links]

- import_tasks: infra-setup/delete/delete_acm.yaml
  tags: [never, teardown-acm, teardown-logging, teardown, teardown-monitoring]

- import_tasks: infra-setup/delete/delete_acs.yaml
  tags: [never, teardown-acs, teardown, teardown-security]

- import_tasks: infra-setup/delete/delete_kubernetes-replicator.yaml
  tags: [never, teardown, teardown-kubernetes-replicator]
