apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: chaos-event-listener
  namespace: tealc-pipelines
spec:
  triggers:
    - name: chaos-pipeline-trigger
      bindings:
        - ref: chaos-command-binding  # Reference of TriggerBinding
      template:
        ref: chaos-smoke-pipeline-template-worker-01  # Reference of TriggerTemplate

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: chaos-command-binding
  namespace: tealc-pipelines
spec:
  params:
    - name: chaosCommand
      value: $(body.chaosCommand)  # Assuming the payload has a field named 'chaosCommand'
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: chaos-smoke-pipeline-template-worker-01
  namespace: tealc-pipelines
spec:
  params:
    - name: chaosCommand  # make sure that this matches TriggerBinding parameter!
      description: Command for chaos testing
      resourcetemplates:
        - apiVersion: tekton.dev/v1beta1
          kind: PipelineRun
          metadata:
            generateName: chaos-smoke-pipeline-run-
          spec:
            pipelineRef:
              name: chaos-smoke-pipeline-worker-01
          workspaces:
          - name: pipeline-ws
            emptyDir: {}
          params:
          - name: chaosCommand
            value: "$(tt.params.chaosCommand)"