apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: chaos-event-listener
  namespace: tealc-pipelines
spec:
  triggers:
    - name: chaos-pipeline-trigger
      bindings:
        - ref: chaos-command-binding  # Reference of TriggerBinding
      template:
        ref: chaos-smoke-pipeline-template-worker-01  # Reference of TriggerTemplate
