apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: chaos-smoke-pipeline-template-worker-01
  namespace: tealc-pipelines
spec:
  params:
  - name: chaosCommand  # make sure that this matches TriggerBinding parameter!
    description: Command for chaos testing
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: chaos-smoke-pipeline-run-
      spec:
        pipelineRef:
          name: chaos-smoke-pipeline-worker-01
        workspaces:
          - name: pipeline-ws
            emptyDir: {}
        params:
          - name: chaosCommand
            value: "$(tt.params.chaosCommand)"