apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secret-copy-task
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: task-ws
  steps:
    - name: tealc-clone
      image: quay.io/rh_integration/strimzi-tools:latest
      script: |
        export CURRENT_DIR=$(workspaces.task-ws.path)/tealc
        git clone https://github.com/ExcelentProject/tealc.git $CURRENT_DIR
    - name: copy-secrets
      env:
        - name: SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: worker-03-tekton
              key: username
        - name: SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: worker-03-tekton
              key: password
        - name: SOURCE_URL
          valueFrom:
            secretKeyRef:
              name: worker-03-tekton
              key: server
        - name: TARGET_USER
          valueFrom:
            secretKeyRef:
              name: worker-02-tekton
              key: username
        - name: TARGET_PASS
          valueFrom:
            secretKeyRef:
              name: worker-02-tekton
              key: password
        - name: TARGET_URL
          valueFrom:
            secretKeyRef:
              name: worker-02-tekton
              key: server
        - name: SOURCE_NAMESPACE
          value: "strimzi-kafka"
        - name: TARGET_NAMESPACE
          value: "strimzi-kafka"
        - name: LABEL_SELECTOR
          value: "strimzi.io/cluster=heimdall"
      image: quay.io/rh_integration/strimzi-tools:latest
      script: |
        $(workspaces.task-ws.path)/tealc/scripts/copy-secrets.sh
        echo "[INFO] Done!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secret-copy-pipeline
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: copy-secret
      taskRef:
        name: secret-copy-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: secret-copy-trigger-template
  labels:
    project: tealc
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: secret-copy-
        labels:
          app: tealc
      spec:
        pipelineRef:
          name: secret-copy-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: pipeline-ws
            volumeClaimTemplate:
              metadata:
                name: secret-copy-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: secret-copy-triggerbinding
  labels:
    project: tealc
spec:
  params:
    - name: message
      value: $(body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: secret-copy
  labels:
    listener: tealc
    project: tealc
spec:
  serviceAccountName: pipeline
  triggers:
    - name: secret-copy-webhook
      bindings:
        - ref: secret-copy-triggerbinding
      template:
        ref: secret-copy-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-secret-copy
  labels:
    project: tealc
spec:
  to:
    kind: Service
    name: el-secret-copy
    weight: 100
  port:
    targetPort: http-listener


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-copy
  labels:
    project: tealc
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: workspace
              emptyDir: {}
          containers:
            - name: trigger
              image: quay.io/rh_integration/strimzi-tools:latest
              command:
                - /bin/sh
              args:
                - -ce
                - |
                  cat <<EOF > /workspace/post-body.json
                  {}
                  EOF
                  curl -d @/workspace/post-body.json $SINK_URL
              volumeMounts:
                - mountPath: /workspace
                  name: workspace
              env:
                - name: SINK_URL
                  value: "el-secret-copy.tealc.svc.cluster.local:8080"
          restartPolicy: Never