---
- name: Delete argo config
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: absent
    verify_ssl: no
    src: files/argo/install/argocd.yaml

- name: Delete Argo subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_operators_namespace }}"
    state: absent
    verify_ssl: no
    src: files/argo/install/sub.yaml

- name: Delete Argo CSV on Infra cluster
  shell: "oc delete csv -n {{ openshift_operators_namespace }} -l operators.coreos.com/openshift-gitops-operator.openshift-operators=''"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  ignore_errors: true