---
- name: Delete Tekton EventListener
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    api_version: "triggers.tekton.dev/v1alpha1"
    label_selectors: listener=tealc
    verify_ssl: no
    state: absent
    kind: EventListener
  ignore_errors: true

- name: Delete Tekton config
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: absent
    verify_ssl: no
    kind: TektonConfig
    api_version: v1alpha1
    name: config

- name: Delete Tekton subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_operators_namespace }}"
    state: absent
    verify_ssl: no
    src: files/tekton/install/tekton-subscription.yaml

- name: Delete Tekton CSV on Infra cluster
  shell: "oc delete csv -n {{ openshift_operators_namespace }} -l operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators=''"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  ignore_errors: true
