---
- name: "Create central on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acs_namespace }}"
    state: present
    apply: true
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/acs/02-central.yaml.j2
  register: acs_central

- name: Sleep for 30 seconds and continue with play
  wait_for:
    timeout: 30
  when: acs_central.changed

- name: "Wait for Central custom resource on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acs_namespace }}"
    kind: Central
    api_version: platform.stackrox.io/v1alpha1
    name: stackrox-central-services
    wait: true
    verify_ssl: no
    wait_condition:
      type: Deployed
      status: True
      reason: UpgradeSuccessful
  retries: 60
  delay: 10
