---
# For more info see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/clusters/cluster_mce_overview#importing-clusters-auto-import-secret
- name: "Create {{ cluster.name }} namespace on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ cluster.name }}"
    state: present
    verify_ssl: no
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cluster.name }}"

- name: "Create {{ cluster.name }}'s managed cluster on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ cluster.name }}"
    state: present
    apply: true
    template: templates/acm/04-managed-cluster.yaml.j2
    verify_ssl: no

- name: "Create {{ cluster.name }}'s auto-import secret on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ cluster.name }}"
    state: present
    apply: true
    template: templates/acm/03-auto-import-secret.yaml.j2
    verify_ssl: no

- name: "Create {{ cluster.name }}'s klusterlet addon on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ cluster.name }}"
    state: present
    apply: true
    template: templates/acm/05-klusterlet-addon-config.yaml.j2
    verify_ssl: no
