- name: "Wait for Certificate readiness on {{ cluster_name }}"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    namespace: "{{ cm_operator_namespace }}"
    kind: Certificate
    name: ingress-cert-lets-encrypt
    wait: true
    wait_timeout: 600
    wait_sleep: 10
    verify_ssl: no
    wait_condition:
      type: Ready
      status: 'True'
      reason: Ready
