---
- name: "Collect AWS secrets"
  ansible.builtin.set_fact:
    aws_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ aws_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Collect clouds.yaml"
  ansible.builtin.set_fact:
    openstack_clouds_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ openstack_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Collect OpenShift pull secret"
  ansible.builtin.set_fact:
    openshift_pull_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ pull_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Collect Kafka SSH keys"
  ansible.builtin.set_fact:
    kafka_ssh_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ kafka_ssh_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Create $HOME/.config/openstack directory"
  ansible.builtin.file:
    path: $HOME/.config/openstack
    state: directory
    mode: '0755'

- name: "Create $HOME/.config/openstack/clouds.yaml"
  copy:
    content: "{{ openstack_clouds_secret['clouds.yaml'] }}"
    dest: $HOME/.config/openstack/clouds.yaml
