---
- name: "Create or Patch AWS secret"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ aws_secret_name }}"
      data:
        access_key_id: "{{ aws_secret['aws_access_key_id'] | b64encode }}"
        access_key_secret: "{{ aws_secret['aws_secret_access_key'] | b64encode }}"

- name: "Create or Patch clouds.yaml secret"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ openstack_clouds_yaml }}"
      data:
        clouds.yaml: "{{ openstack_clouds_secret['clouds.yaml'] | b64encode }}"

- name: "Create or Patch pull-secret"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ openshift_pull_secret_name }}"
      data:
        .dockerconfigjson: "{{ openshift_pull_secret['pull-secret-json'] | b64encode }}"

- name: "Create or Patch Kafka ssh secret"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ kafka_ssh_secret_name }}"
      data:
        ssh-publickey: "{{ kafka_ssh_secret['pub'] | b64encode }}"
        ssh-privatekey: "{{ kafka_ssh_secret['key'] | b64encode }}"
