kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: tekton-pipelinerun-cleaner
  namespace: tealc
  labels:
    app: tekton-pipelinerun-cleaner
    app.kubernetes.io/component: pipelinerun-cleaner
    app.kubernetes.io/name: tekton-pipelinerun-cleaner
    app.kubernetes.io/part-of: tekton
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl
              image: 'quay.io/tealc/k8s:latest'
              command:
                - /bin/bash
                - '-c'
                - >
                  while read -r PIPELINE; do
                    while read -r PIPELINE_TO_REMOVE; do
                      test -n "${PIPELINE_TO_REMOVE}" || continue;
                      kubectl delete ${PIPELINE_TO_REMOVE} \
                          && echo "$(date -Is) PipelineRun ${PIPELINE_TO_REMOVE} deleted." \
                          || echo "$(date -Is) Unable to delete PipelineRun ${PIPELINE_TO_REMOVE}.";
                    done < <(kubectl get pipelinerun -l tekton.dev/pipeline=${PIPELINE} --sort-by=.metadata.creationTimestamp -o name | head -n -${NUM_TO_KEEP});
                  done < <(kubectl get pipelinerun -o go-template='{{range
                  .items}}{{index .metadata.labels
                  "tekton.dev/pipeline"}}{{"\n"}}{{end}}' | uniq);
              env:
                - name: NUM_TO_KEEP
                  value: '2'
              resources:
                limits:
                  cpu: 100m
                  memory: 64Mi
                requests:
                  cpu: 50m
                  memory: 32Mi
