---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: superuser-event-bus
  labels:
    strimzi.io/cluster: event-bus
spec:
  authentication:
    type: tls
  template:
    secret:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to-matching: "strimzi.io/sync-secrets=true"
