---
- name: "Check if {{ cluster_name }} cluster config exists in {{ hive_namespace }} namespace"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    kind: ClusterDeployment
    name: "{{ cluster_name }}"
    wait: false
    verify_ssl: no
  register: cluster_present
