##############################
# Wait for cluster readiness #
##############################
- name: Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5

- name: "Wait for ClusterDeployment {{ cluster.name }} readiness"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ hive_namespace }}"
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 3600
    verify_ssl: no
    wait_condition:
      type: Provisioned
      status: True
      reason: Provisioned
