---
- name: Create Argo applications for AMQ Streams infra
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    apply: true
    src: "files/argo/applications/amq-streams-infra.yaml"
    verify_ssl: no
