- name: "Get current oauth configuration"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    kind: OAuth
    name: "cluster"
    verify_ssl: no
  ignore_errors: true
  register: oauth_config

- name: "Collect superadmin secrets"
  ansible.builtin.set_fact:
    superadmin_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ superadmin_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"
  when: "oauth_config.resources[0].spec.identityProviders is not defined"

- name: "Add a user to a password file for {{ cluster_name }}"
  shell: "htpasswd -c -B -b users.htpasswd {{ superadmin_secret['username'] }} {{ superadmin_secret['password'] }}"
  when: "oauth_config.resources[0].spec.identityProviders is not defined"

- name: "Create secret with superadmin user on {{ cluster_name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "superadmin-secret"
        namespace: "openshift-config"
      data:
        htpasswd: "{{ lookup('file', 'users.htpasswd' ) | b64encode }}"
  when: "oauth_config.resources[0].spec.identityProviders is not defined"

- name: "Update on {{ cluster_name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    namespace: "openshift-config"
    state: present
    merge_type:
      - merge
    verify_ssl: no
    template: templates/hive/oauth.yaml.j2
  when: "oauth_config.resources[0].spec.identityProviders is not defined"

- name: "Add admin rights to superadmin on {{ cluster_name }}"
  shell: "oc adm policy add-cluster-role-to-user cluster-admin {{ superadmin_secret['username'] }} --rolebinding-name=cluster-admin"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ cluster_name }}"
  when: "oauth_config.resources[0].spec.identityProviders is not defined"
