- name: "Get current oauth configuration"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    kind: OAuth
    name: "cluster"
    verify_ssl: no
  ignore_errors: true
  register: oauth_config

- name: "Collect htpasswd users secrets"
  ansible.builtin.set_fact:
    htpasswd_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ htpasswd_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Collect superadmin secrets"
  ansible.builtin.set_fact:
    superadmin_secret: "{{ lookup('community.hashi_vault.hashi_vault', 
    'secret={{ superadmin_secret_path }} 
    auth_method=approle 
    role_id={{ vault_role_id }} 
    secret_id={{ vault_secret_id }} 
    url={{ vault_url }}
    return_format=dict',
    validate_certs=False) }}"

- name: "Set facts for users_grups"
  set_fact:
    users_groups: "{{ htpasswd_secret['users_groups'] | from_yaml }}"

- name: "Clear htpasswd file"
  ansible.builtin.file:
    path: "{{ htpasswd_file }}"
    state: absent

- name: "Create htpasswd file"
  ansible.builtin.file:
    path: "{{ htpasswd_file }}"
    state: touch

- name: "Add users to htpasswd"
  shell: "htpasswd -B -b {{ htpasswd_file }} {{ user.name }} {{ user.password }}"
  loop: "{{ users_groups['users'] }}"
  loop_control:
    loop_var: user

- name: "Create secret with htpasswd user on {{ cluster_name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "htpasswd-secret"
        namespace: "openshift-config"
      data:
        htpasswd: "{{ lookup('file', '{{ htpasswd_file }}' ) | b64encode }}"

- name: "Update on {{ cluster_name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    namespace: "openshift-config"
    state: present
    merge_type:
      - merge
    verify_ssl: no
    template: templates/hive/oauth.yaml.j2

- name: "Add admin rights to htpasswd on {{ cluster_name }}"
  shell: "oc adm policy add-cluster-role-to-user cluster-admin {{ superadmin_secret['username'] }} --rolebinding-name=cluster-admin"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ cluster_name }}"

- name: "Create groups of predefined-users"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster_name }}"
    state: present
    verify_ssl: no
    template: templates/hive/groups.yaml.j2
  vars:
    groupName: "{{ group.name }}"
    groupUsers: "{{ group.users }}"
  loop: "{{ users_groups['groups'] }}"
  loop_control:
    loop_var: group
