---
- name: Create Argo applications for ODH
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    apply: true
    template: "templates/argo/applications/open-data-hub/{{ file_template }}"
    verify_ssl: no
  loop:
    - open-data-hub-operator.yaml.j2
    - open-data-hub-dependencies.yaml.j2
    - open-data-hub-resources.yaml.j2
  loop_control:
    loop_var: file_template
  vars:
    cluster: "worker-03"
