---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: open-data-hub-files-update-trigger
  labels:
    project: tealc
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: workspace
              emptyDir: {}
            - name: configmap-volume
              configMap:
                defaultMode: 0755
                name: odh-image-changer
          containers:
            - name: trigger
              image: quay.io/tealc/tealc-ee:latest
              command:
                - /workspace/entrypoint.sh
              volumeMounts:
                - mountPath: /workspace
                  name: workspace
                - name: configmap-volume
                  mountPath: /workspace/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              env:
                - name: WORKSPACE
                  value: "/workspace"
              resources:
                limits:
                  cpu: 100m
                  memory: 64Mi
                requests:
                  cpu: 50m
                  memory: 32Mi
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odh-image-changer
  labels:
    project: tealc
data:
  entrypoint.sh: |
    #!/bin/bash
    
    set -x
    set -e
    
    echo "[INFO] Going to trigger Operator images update"
    curl -d '{"trigger-template": "image-update","params": {"image": "operator"}}' el-open-data-hub-files-update-event-listener.tealc-pipelines.svc.cluster.local:8080
