apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: open-data-hub-files-update-pipeline
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: odh
      workspaces:
        - name: pipeline-ws
          workspace: pipeline-ws
      taskSpec:
        workspaces:
          - name: pipeline-ws
        steps:
          - name: tealc-clone
            image: quay.io/wire/alpine-git
            script: |
              export CURRENT_DIR=$(workspaces.pipeline-ws.path)/tealc
              git clone https://github.com/ExcelentProject/tealc.git $CURRENT_DIR
          - name: images-update
            env:
              - name: BRANCH
                value: "incubation"
              - name: GITHUB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: github-secret
                    key: USERNAME
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-secret
                    key: TOKEN
            image: quay.io/tealc/apophis:latest
            script: |
              $(workspaces.pipeline-ws.path)/tealc/scripts/generate-odh.sh
              echo "[INFO] Done!"
  finally:
    - name: notify-slack
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: webhook-secret
        - name: message
          value: "Pipeline `$(context.pipeline.name)`:`$(context.pipelineRun.name)` failed!"

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: open-data-hub-files-update-trigger-template
  labels:
    project: tealc
spec:
  params:
    - name: message
      description: Message from quay.io
      default: empty
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: open-data-hub-files-update-
        labels:
          app: tealc
      spec:
        pipelineRef:
          name: open-data-hub-files-update-pipeline
        workspaces:
          - name: pipeline-ws
            volumeClaimTemplate:
              metadata:
                name: odh-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi


---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: open-data-hub-files-update-triggerbinding
  labels:
    project: tealc
spec:
  params:
    - name: message
      value: $(body)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: open-data-hub-files-update-event-listener
  labels:
    listener: tealc
    project: tealc
spec:
  triggers:
    - name: open-data-hub-files-update-webhook
      bindings:
        - ref: open-data-hub-files-update-triggerbinding
      template:
        ref: open-data-hub-files-update-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "64Mi"
                    cpu: "50m"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-open-data-hub-files-update-event-listener
  labels:
    project: tealc
spec:
  to:
    kind: Service
    name: el-open-data-hub-files-update-event-listener
    weight: 100
  port:
    targetPort: http-listener
