---
- name: "Delete {{ rhbk_namespace}} namespace on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ rhbk_namespace }}"
    api_version: v1
    kind: Namespace
    verify_ssl: no
    state: absent