apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: tealc-gitops
  labels:
    project: tealc
spec:
  server:
    autoscale:
      enabled: true
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
      tls:
        termination: reencrypt
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  applicationSet:
    resources:
      limits:
        cpu: '3'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
  rbac:
    defaultPolicy: "role:readonly"
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, system:authenticated:oauth, role:admin
    scopes: '[groups]'
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  dex:
    openShiftOAuth: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  redis:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    processors: {}
    logLevel: debug
    resources:
      limits:
        cpu: '2'
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
    tls:
      ca:
        secretName: tealc-signed-certificate
