apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: strimzi-infra
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/ExcelentProject/sokar
              revision: HEAD
              files:
                - path: "strimzi/**/argo-config.yaml"
          - clusters:
              selector:
                matchLabels:
                  environment: 'upstream-latest'
  template:
    metadata:
      name: '{{appname}}-{{name}}'
      labels:
        project: tealc
        app: strimzi
    spec:
      project: default
      source:
        repoURL: https://github.com/ExcelentProject/sokar
        targetRevision: HEAD
        path: '{{source}}'
        directory:
          recurse: true
          exclude: '{argo-config.yaml}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            project: tealc
      destination:
        name: '{{name}}'
        namespace: '{{namespace}}'
