apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: skodjob
spec:
  # For more info see https://argoproj.github.io/argo-events/eventbus/kafka/
  kafka:
    url: event-bus-kafka-bootstrap.strimzi-event-bus.svc.cluster.local:9093
    tls:
      caCertSecret:
        name: event-bus-cluster-ca-cert
        key: ca.crt
      clientCertSecret:
        name: superuser-event-bus
        key: user.crt
      clientKeySecret:
        name: superuser-event-bus
        key: user.key
