apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-e2e-metrics-collector
  labels:
    app: strimzi-e2e-metrics-collector
---
kind: Service
apiVersion: v1
metadata:
  name: strimzi-e2e-metrics-collector
  labels:
    app: strimzi-e2e-metrics-collector
spec:
  ports:
    - port: 8080
      name: metrics
      protocol: TCP
      targetPort: 8080
  selector:
    app: strimzi-e2e-metrics-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-e2e-metrics-collector
  labels:
    app: strimzi-e2e-metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-e2e-metrics-collector
  template:
    metadata:
      labels:
        app: strimzi-e2e-metrics-collector
        skodjob/kind: strimzi-e2e-exporter
    spec:
      serviceAccountName: strimzi-e2e-metrics-collector
      containers:
        - name: strimzi-e2e-metrics-collector
          # TODO - move to different org and use skodjob-ee
          image: quay.io/tealc/metrics-collector@sha256:f7adc0b119f1e4fb7df05575e504fd977e57d7fd79e21a1fa135ade15b27bb85
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
  strategy:
    type: Recreate
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: skodjob
  name: strimzi-e2e-metrics
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      skodjob/kind: strimzi-e2e-exporter
