---
- name: Delete console link for skodjob applications
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: absent
    template: "{{ item }}"
    verify_ssl: no
  with_fileglob: 'templates/console-link/*.j2'