---
# TODO check if we can delete it
- name: Create thor Tekton pipelines
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "{{ item }}"
  with_fileglob: 'files/tekton/pipelines/thor/*.yaml'
