---
- name: "Delete OpenShift Logging instance on {{ clusterName }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ clusterName }}"
    namespace: "{{ openshift_logging_namespace }}"
    state: present
    apply: true
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/logging/install/cluster-logging/02-cluster-logging-instance.yaml.j2

- name: "delete OpenShift Logging operator group and subscription on {{ clusterName }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ clusterName }}"
    namespace: "{{ openshift_logging_namespace }}"
    state: present
    apply: true
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/logging/install/cluster-logging/00-operator-group.yaml.j2
    - templates/logging/install/cluster-logging/01-openshift-logging-subscription.yaml.j2
  register: cluster_logging
