---
- name: Create monitoring namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    verify_ssl: no
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ infra_monitoring_namespace }}"
        labels:
          'argocd.argoproj.io/managed-by': "{{ infra_argo_namespace }}"

- name: Enable & configure user-workload on infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    apply: true
    template: "{{ item }}"
    verify_ssl: no
  vars:
    clusterName: "{{ infra_context_name }}"
  loop:
    - templates/cluster-monitoring-cm.yaml.j2
    - templates/user-workload-monitoring-cm.yaml.j2


- name: Create monitoring namespace on worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    name: "{{ worker.value.monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    verify_ssl: no
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Enable user-workload on worker cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    namespace: "openshift-monitoring"
    state: present
    apply: true
    template: templates/cluster-monitoring-cm.yaml.j2
    verify_ssl: no
  vars:
    clusterName: "{{ worker.value.name }}"
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Configure user-workload on worker cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    state: present
    apply: true
    template: templates/user-workload-monitoring-cm.yaml.j2
    verify_ssl: no
  vars:
    clusterName: "{{ worker.value.name }}"
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Setup Grafana access on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: present
    apply: true
    template: templates/grafana/grafana-setup.yaml.j2
    verify_ssl: no

- name: Setup Grafana access on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    namespace: "{{ worker.value.monitoring_namespace }}"
    state: present
    template: templates/grafana/grafana-setup.yaml.j2
    verify_ssl: no
    apply: true
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Install Grafana operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: present
    template: templates/grafana/grafana-operator.yaml.j2
    verify_ssl: no
    apply: true

- name: Sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20

- name: Wait for Grafana operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    kind: Deployment
    name: grafana-operator-controller-manager
    wait: true
    apply: true
    verify_ssl: no
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Deploy Grafana instance on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: present
    apply: true
    template: templates/grafana/grafana.yaml.j2
    verify_ssl: no

- name: Create data-sources on Infra cluster
  include_tasks: deploy-data-source.yaml
  loop:
    - {name: "{{ workers.main_cluster.name }}", sa_namespace: "{{ workers.main_cluster.monitoring_namespace }}",
       monitoring_namespace: "{{ infra_monitoring_namespace }}",
       context: "{{ infra_context_name }}",
       sa_name: "grafana-serviceaccount",
       url: "https://thanos-querier-openshift-monitoring.apps.{{ workers.main_cluster.name }}.strimzi.app-services-dev.net:443"}
    - {name: "{{ workers.release_cluster.name }}", sa_namespace: "{{ workers.release_cluster.monitoring_namespace }}",
       sa_name: "grafana-serviceaccount",
       monitoring_namespace: "{{ infra_monitoring_namespace }}",
       context: "{{ infra_context_name }}",
       url: "https://thanos-querier-openshift-monitoring.apps.{{ workers.release_cluster.name }}.strimzi.app-services-dev.net:443"}
    - {name: "{{ workers.downstream_cluster.name }}", sa_namespace: "{{ workers.downstream_cluster.monitoring_namespace }}",
       monitoring_namespace: "{{ infra_monitoring_namespace }}",
       sa_name: "grafana-serviceaccount",
       context: "{{ infra_context_name }}",
       url: "https://thanos-querier-openshift-monitoring.apps.{{ workers.downstream_cluster.name }}.strimzi.app-services-dev.net:443"}
    - {name: "{{ infra_context_name }}", sa_namespace: "{{ infra_user_namespace }}",
       sa_name: "tealc-sa",
       monitoring_namespace: "{{ infra_monitoring_namespace }}",
       context: "{{ infra_context_name }}",
       url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"}
  loop_control:
    loop_var: target

- name: Configure Alertmanager to for sending alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    verify_ssl: no
    apply: true
    template: templates/alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ infra_context_name }}"

- name: Configure Alertmanager to for sending alerts on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    state: present
    verify_ssl: no
    apply: true
    template: templates/alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ worker.value.name }}"
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Configure Grafana dashboards and Prometheus alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: present
    verify_ssl: no
    apply: true
    src: "templates/argo/metrics/{{ item }}"
  loop:
    - argo-dashboard-cm.yaml
    - grafana-argo-dashboards.yaml

- name: Configure Prometheus alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    verify_ssl: no
    apply: true
    src: "templates/argo/metrics/{{ item }}"
  loop:
    - alerts.yaml
