apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-network-producers-worker-01
  namespace: tealc-pipelines
spec:
  schedule: "0 */8 * * *"  # Runs every 8 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trigger
              image: appropriate/curl
              command:
                - /bin/sh
                - -c
                - >
                  curl -X POST
                  -H 'Content-Type: application/json'
                  -d '{"chaosCommand": "--network-chaos kafka-producers-fast-internal-network-delay-all --sut-namespace strimzi-kafka --clients-namespace strimzi-clients --metrics-selector "anubis-pool-.* --enable-probes" }'  
                  http://el-chaos-event-listener.tealc-pipelines.svc.cluster.local:8080
          restartPolicy: OnFailure