apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: twitter-app-deployment-image-update-task
  labels:
    project: tealc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  workspaces:
    - name: task-ws
  steps:
    - name: tealc-clone
      image: quay.io/rh_integration/strimzi-tools:latest
      script: |
        export CURRENT_DIR=$(workspaces.task-ws.path)/tealc
        git clone https://github.com/ExcelentProject/tealc.git $CURRENT_DIR
    - name: images-update
      env:
        - name: CURRENT_DEPLOYMENT_REPO
          value: "https://github.com/ExcelentProject/sokar"
        - name: TARGET_ORG_REPO
          value: "quay.io/tealc"
        - name: BRANCH
          value: main
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: USERNAME
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: TOKEN
      image: quay.io/tealc/apophis:latest
      script: |
        FILE_NAME=strimzi/twitter-connector/apps/01-twitter-messages-parser.yaml $(workspaces.task-ws.path)/tealc/image-update/clients-image-update.sh
        echo "[INFO] Done!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: twitter-app-deployment-image-update-pipeline
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    project: tealc
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: twitter-app-image-update
      taskRef:
        name: twitter-app-deployment-image-update-task
      workspaces:
        - name: task-ws
          workspace: pipeline-ws
  finally:
    - name: notify-slack
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: send-to-webhook-slack
      params:
        - name: webhook-secret
          value: webhook-secret
        - name: message
          value: "Pipeline run `$(context.pipelineRun.name)` failed!"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: twitter-app-deployment-image-update-trigger-template
  labels:
    project: tealc
spec:
  params:
    - name: message
      description: Message from quay.io
      default: empty
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: twitter-app-deployment-image-update-
        labels:
          app: tealc
      spec:
        pipelineRef:
          name: twitter-app-deployment-image-update-pipeline
        workspaces:
          - name: pipeline-ws
            volumeClaimTemplate:
              metadata:
                name: clients-pvc
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: twitter-app-deployment-image-update-triggerbinding
  labels:
    project: tealc
spec:
  params:
    - name: message
      value: $(body)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: twitter-image-update-event-listener
  labels:
    listener: tealc
    project: tealc
spec:
  triggers:
    - name: twitter-app-deployment-image-update-webhook
      bindings:
        - ref: twitter-app-deployment-image-update-triggerbinding
      template:
        ref: twitter-app-deployment-image-update-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "64Mi"
                    cpu: "50m"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-twitter-image-update-event-listener
  labels:
    project: tealc
spec:
  to:
    kind: Service
    name: el-twitter-image-update-event-listener
    weight: 100
  port:
    targetPort: http-listener
