---
- name: Delete Grafana access on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana-setup.yaml.j2

- name: Delete Grafana access on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ worker.value.monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana-setup.yaml.j2
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana-operator.yaml.j2

- name: Delete Grafana operator on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    namespace: "{{ worker.value.monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana-operator.yaml.j2
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana instance on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana.yaml.j2

- name: Delete Grafana instance on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    namespace: "{{ worker.value.monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana/grafana.yaml.j2
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Remove Alertmanager configuration for sending alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: absent
    verify_ssl: no
    template: templates/acm/09-alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ infra_context_name }}"
    namespace: "open-cluster-management-observability"
    suffix: "config"

- name: Remove Alertmanager configuration for sending alerts on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    state: absent
    verify_ssl: no
    template: templates/acm/09-alert-manager-configuration.yaml.j2
  vars:
    clusterName: "{{ worker.value.name }}"
    namespace: "openshift-monitoring"
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Delete Grafana data-source on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana-data-source.yaml.j2

- name: Delete Grafana data-source on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    namespace: "{{ worker.value.monitoring_namespace }}"
    state: absent
    verify_ssl: no
    template: templates/grafana-data-source.yaml.j2
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker

- name: Delete monitoring namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    verify_ssl: no

- name: Delete monitoring namespaces on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.value.name }}"
    name: "{{ worker.value.monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    verify_ssl: no
  loop: "{{ workers | dict2items }}"
  loop_control:
    loop_var: worker
