---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-serviceaccount
  namespace: default
  labels:
    app: strimzi
    namespace: default
    project: skodjob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-binding
  labels:
    app: strimzi
    project: skodjob
subjects:
  - kind: ServiceAccount
    name: access-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: access-serviceaccount
  namespace: default
  labels:
    app: strimzi
    project: skodjob
  annotations:
    kubernetes.io/service-account.name: access-serviceaccount