---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: open-data-hub-files-update-start
  labels:
    app: skodjob
    project: skodjob
spec:
  pipelineRef:
    name: open-data-hub-files-update-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: odh-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1000Mi
