---
- name: "Delete central on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acs_namespace }}"
    state: absent
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/acs/02-central.yaml.j2
  register: acs_operator

- name: "Delete ACS operator group and subscription on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acs_namespace }}"
    state: absent
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/acm/00-operator-group.yaml.j2
    - templates/acm/01-acs-subscription.yaml.j2

- name: "Delete ACS namespace on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ acs_namespace }}"
    api_version: v1
    kind: Namespace
    verify_ssl: no
    state: absent
