---
- name: Check that kubeconfigs exists
  stat:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_exists

- name: Check that kubeconfigs works
  shell: "oc get ns || oc get po"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_works
  ignore_errors: yes
  when: kubeconfig_exists.stat.exists

- name: Create kubeconfig for Infra
  shell: " oc login -u {{ infra_username }} -p {{ infra_password }} --insecure-skip-tls-verify=true {{ infra_api_url }} --namespace {{ infra_ci_namespace | default('default') }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: (not kubeconfig_exists.stat.exists or kubeconfig_works.rc != 0) and infra_access_token is not defined

- name: Create kubeconfig for Infra
  shell: " oc login --token {{ infra_access_token }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: (not kubeconfig_exists.stat.exists or kubeconfig_works.rc != 0) and infra_access_token is defined

- name: Set proper rights for kubeconfigs on Infra cluster
  file:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    mode: '0755'

- include_tasks:
    file: setup_cluster_kubeconfig.yaml
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: cluster

- name: Check cluster type
  shell: kubectl api-versions
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: cluster_type

- name: Set facts for cluster type
  set_fact: is_kubernetes="{{ 'openshift' not in cluster_type.stdout }}"
