---
- name: Check that kubeconfigs exists
  stat:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_exists

- name: Check that kubeconfigs works
  shell: "oc get ns || oc get po"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_works
  ignore_errors: yes
  when: kubeconfig_exists.stat.exists

- name: Create kubeconfig for Infra
  shell: " oc login -u {{ infra_username }} -p {{ infra_password }} --insecure-skip-tls-verify=true {{ infra_api_url }} --namespace {{ infra_ci_namespace | default('default') }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: (not kubeconfig_exists.stat.exists or kubeconfig_works.rc != 0) and infra_access_token is not defined

- name: Create kubeconfig for Infra
  shell: " oc login --token {{ infra_access_token }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: (not kubeconfig_exists.stat.exists or kubeconfig_works.rc != 0) and infra_access_token is defined

- name: Create kubeconfig for Workers
  shell: "oc login -u {{ item.value.username }} -p {{ item.value.password }} --insecure-skip-tls-verify=true {{ item.value.api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.value.name }}"
  loop: "{{ workers | dict2items }}"
  when: item.value.access_token is not defined

- name: Create kubeconfig for Workers
  shell: "oc login --token {{ item.value.access_token }} --insecure-skip-tls-verify=true {{ item.value.api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.value.name }}"
  loop: "{{ workers | dict2items }}"
  when: item.value.access_token is defined

- name: Set proper rights for kubeconfigs on Infra cluster
  file:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    mode: '0755'

- name: Set proper rights for kubeconfigs on Worker clusters
  file:
    path: "{{ kubeconfig_path }}/{{ item.value.name }}"
    mode: '0755'
  loop: "{{ workers | dict2items }}"

- name: Check cluster type
  shell: kubectl api-versions
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: cluster_type

- name: Set facts for cluster type
  set_fact: is_kubernetes="{{ 'openshift' not in cluster_type.stdout }}"
