# Get cluster URL
- name: "Get cluster {{ cluster.name }} API URL"
  shell: "oc get clusterdeployment {{ cluster.name }} -n {{ hive_namespace }} -o=jsonpath='{.status.apiURL}'"
  register: serverUrl_output

- name: "Get cluster {{ cluster.name }} provisionRef name"
  shell: "oc get clusterdeployment {{ cluster.name }} -n {{ hive_namespace }} -o=jsonpath='{.status.provisionRef.name}'"
  register: provisionRefName_output

- name: "Extract kubeconfig for cluster {{ cluster.name }}"
  shell: "oc extract secret/{{ provisionRefName.stdout }}-admin-kubeconfig -n {{ hive_namespace }} --to=- --keys=kubeconfig"
  register: kubeconfig_output

- name: "Update facts for {{ cluster.name }}"
  ansible.utils.update_fact:
    updates:
      - path: "clusters_dict.{{ cluster.name }}.serverUrl"
        value: "{{ serverUrl_output.stdout }}"
      - path: "clusters_dict.{{ cluster.name }}.provisionRefName"
        value: "{{ provisionRefName_output.stdout }}"
  register: updated_data

- set_fact:
    clusters_dict: "{{ updated_data.clusters_dict }}"

- name: Create kubeconfig for {{ cluster.name }}
  copy:
    content: "{{ kubeconfig_output.stdout }}"
    dest: "{{ kubeconfig_path }}/{{ cluster.name }}"
#  delegate_to: localhost

- name: Set proper rights for kubeconfigs on {{ cluster.name }}
  file:
    path: "{{ kubeconfig_path }}/{{ cluster.name }}"
    mode: '0755'
