---
# For more info see https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/install/installing#installing-while-connected-online
- name: "Create ACM namespace on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ acm_namespace }}"
    api_version: v1
    kind: Namespace
    verify_ssl: no
    state: present

- name: "Create ACM operator group and subscription on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acm_namespace }}"
    state: present
    apply: true
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/acm/00-operator-group.yaml.j2
    - templates/acm/01-acm-subscription.yaml.j2

- name: "Create multi-cluster-hub on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acm_namespace }}"
    state: present
    apply: true
    verify_ssl: no
    template: "{{ item }}"
  loop:
    - templates/acm/02-multicluster-hub.yaml.j2
  register: acm_operator

- name: Sleep for 30 seconds and continue with play
  wait_for:
    timeout: 30
  when: acm_operator.changed

- name: "Wait for MultiClusterHub custom resource on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ acm_namespace }}"
    kind: MultiClusterHub
    name: multiclusterhub
    wait: true
    verify_ssl: no
    wait_condition:
      type: Complete
      status: True
      reason: ComponentsAvailable
  retries: 60
  delay: 10
