---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Include configuration
      include_vars: ./secrets/clusters.yaml
      tags:
        - always
  roles:
    - role: automation-hub
