---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Include configuration
      include_vars: ./examples/clusters.yaml
      tags:
        - always
  roles:
    - role: tealc
      become: yes