---
# defaults file
infra_monitoring_namespace: tealc-monitoring
infra_ci_namespace: tealc-pipelines
infra_workflow_namespace: skodjob-ci
infra_argo_namespace: tealc-gitops

openshift_pipelines_namespace: openshift-pipelines
openshift_operators_namespace: openshift-operators

route: empty
access_token: empty

htpasswd_file: /tmp/htpasswd

# GitOps
gitops_channel_version: 1.13
gitops_version: 1.13.1

# ACM
acm_version: 2.11
loki_version: 6.0
openshift_logging_version: 6.0
acm_namespace: tealc-rhacm
acm_observability_namespace: open-cluster-management-observability

# ACS
acs_version: 4.5
acs_namespace: tealc-rhacs
acs_stackrox_namespace: stackrox
acs_api_token_file: "{{ playbook_dir }}/acs_api_token"
acs_init_secrets: "{{ playbook_dir }}/init-bundle.yaml"

# Cert Manager configs
cm_namespace: cert-manager
cm_operator_namespace: cert-manager-operator
cm_route53_credentials: route53-le-credentials
cm_route53_secret_key_ref: secret-key
cm_route53_access_key_ref: access-key
cm_certificate_secret: tealc-signed-certificate
cm_version: 1.14.0

# Strimzi
strimzi_operator_namespace: strimzi-operator
strimzi_kafka_namespace: strimzi-event-bus
strimzi_drain_cleaner_namespace: strimzi-operator
