---
- name: "Create namespaces on Infra cluster"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    verify_ssl: no
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
        labels:
          project: "skodjob"
  loop:
    - "{{ infra_ci_namespace }}"
    - "{{ openshift_pipelines_namespace }}"
    - "{{ infra_argo_namespace }}"

- name: "Create ServiceAccount for remote access on {{ worker.name }}"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    namespace: "default"
    state: present
    verify_ssl: no
    src: templates/remote_access_sa.yaml

- name: "Export access token on {{ worker.name }}"
#  shell: "oc serviceaccounts get-token access-serviceaccount -n default"
  shell: "oc get  $(oc get secret -o name -n default | grep access-serviceaccount-token) -n default -o=jsonpath='{.data.token}' | base64 -d"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ worker.name }}"
  register: "access_token_out"

- name: "Set facts for route host - {{ worker.name }}"
  set_fact: access_token="{{ access_token_out.stdout }}"

- name: "Update facts for {{ worker.name }}"
  ansible.utils.update_fact:
    updates:
      - path: "clusters_dict['{{ worker.name }}'].token"
        value: "{{ access_token }}"
  register: updated_data

- set_fact:
    clusters_dict: "{{ updated_data.clusters_dict }}"

- name: Check that token exists
  fail:
    msg: "Token is not properly stored!\n{{ access_token }}"
  when: access_token | length == 0

- name: Create Github access secret in infra namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "{{ github_secret_path }}"
    verify_ssl: no
    apply: true

- name: Create tealc-install access secret in infra namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "{{ tealc_git_crypt_key }}"
    verify_ssl: no
    apply: true

- name: Create Github access secret in openshift-pipelines namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: "{{ github_secret_path }}"
    verify_ssl: no
    apply: true

- name: Create Tekton secret in tekton namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    template: templates/tekton/install/tekton-secret.yaml.j2
    verify_ssl: no
    apply: true

- name: Create Tekton secret in openshift-pipelines namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    template: templates/tekton/install/tekton-secret.yaml.j2
    verify_ssl: no
    apply: true

- name: Create cluster Argo access secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    template: templates/cluster-secret.yaml.j2
    verify_ssl: no
    apply: true

- name: Create Quay access secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ worker.name }}"
    namespace: "default"
    state: present
    verify_ssl: no
    apply: true
    src: "{{ quay_io_secret_path }}"

- name: "Create ODH data connection secret"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}/{{ clusterName }}"
    namespace: "default"
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "odh-s3-data-connection"
        annotations:
          kubed.appscode.com/sync: "app=open-data-hub"
          opendatahub.io/connection-type: s3
          openshift.io/display-name: "{{ bucketname }}"
        labels:
          app: open-data-hub
          project: skodjob
          opendatahub.io/dashboard: 'true'
          opendatahub.io/managed: 'true'
      data:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id | b64encode }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_access_key_secret | b64encode }}"
        AWS_S3_ENDPOINT: "{{ aws_endpoint | b64encode }}"
        AWS_DEFAULT_REGION: "{{ aws_region | b64encode }}"
        AWS_S3_BUCKET: "{{ bucketname | b64encode }}"
  vars:
    bucketname: "tealc-models"
  loop:
    - "worker-03"
  loop_control:
    loop_var: clusterName
