apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-webhook-slack
  labels:
    app.kubernetes.io/version: "0.1"
    project: skodjob
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: messaging
    tekton.dev/displayName: "Send message to Slack Channel"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"

spec:
  description: >-
    This task send notification to Slack. Note that every message will contains button co do not forget to fill URL and title for the button.
  params:
    - name: webhook-secret
      type: string
      description: secret name of the slack app webhook URL (key is url)
    - name: message
      type: string
      description: plain text message
    - name: title
      type: string
      description: plain text title
    - name: status
      type: string
      description: Status of the reported task
      default: '#439FE0'
    - name: button_url
      type: string
      description: URL for the button
    - name: button_text
      type: string
      description: Title of the button
  steps:
    - name: post
      image: quay.io/skodjob/skodjob-ee:latest
      script: |
        #!/usr/bin/env sh

        # Default color is blue
        COLOR="#439FE0"
        if [ "$STATUS" = "Failed" ]; then
          # Set red color
          COLOR="#FF0000"
        elif [ "$STATUS" = "Succeeded" ]; then 
          # Green
          COLOR="#008000"
        fi
        echo "Status: $STATUS"
        echo "Used color: $COLOR"
        
        JSON="{\"attachments\":[{\"color\":\"${COLOR}\",\"blocks\":[{\"type\":\"header\",\"text\":{\"type\":\"plain_text\",\"text\":\"${TITLE}\",\"emoji\":true}},{\"type\":\"divider\"},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${MESSAGE}\"}},{\"type\":\"actions\",\"elements\":[{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"${BUTTON_TEXT}\",\"emoji\":true},\"url\":\"${BUTTON_URL}\"}]}]}]}"
        curl -X POST -H 'Content-Type: application/json' --data "${JSON}" "${URL}"
      env:
        - name: URL
          valueFrom:
            secretKeyRef:
              name: $(params.webhook-secret)
              key: url
        - name: TITLE
          value: $(params.title)
        - name: MESSAGE
          value: $(params.message)
        - name: STATUS
          value: $(params.status)
        - name: BUTTON_URL
          value: $(params.button_url)
        - name: BUTTON_TEXT
          value: $(params.button_text)
