- name: Deploy Kubernetes Replicator on infra clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "kube-system"
    state: present
    apply: true
    template: templates/kubernetes-replicator/kubernetes-replicator.yaml.j2
    verify_ssl: no

- name: Deploy Kubernetes Replicator on worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ cluster.name }}"
    namespace: "kube-system"
    state: present
    apply: true
    template: templates/kubernetes-replicator/kubernetes-replicator.yaml.j2
    verify_ssl: no
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: cluster
