---
- name: Create {{ infra_workflow_namespace }} namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    verify_ssl: no
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ infra_workflow_namespace }}"
        labels:
          project: "skodjob"
          secret: "cert-manager"

- name: Clean helm releases for workflows
  shell: "oc delete secret -l owner=helm -n {{ infra_workflow_namespace }} || true"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"

- name: Make default SA admin in {{ infra_workflow_namespace }} namespace
  shell: "oc adm policy add-role-to-user admin system:serviceaccount:{{ infra_workflow_namespace }}:default -n {{ infra_workflow_namespace }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"

- name: Add Argo Helm Repo
  kubernetes.core.helm_repository:
    name: argo
    url: https://argoproj.github.io/argo-helm

- name: Install Argo Workflow
  kubernetes.core.helm:
    name: "{{ infra_workflow_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    chart_ref: argo/argo-workflows
    release_namespace: "{{ infra_workflow_namespace }}"
    create_namespace: True
    purge: True
    force: True
    wait: True
    replace: True
    update_repo_cache: True
    values:
      commonLabels:
        app: skodjob
        project: skodjob
      server:
        replicas: 3
        authModes:
          - client
          - server
        ingress:
          enabled: true
          hosts:
            - "{{ argo_workflow_url }}"
          tls:
            - secretName: "{{ cm_certificate_secret }}"
              hosts:
                - "{{ argo_workflow_url }}"

- name: Install Argo Events
  kubernetes.core.helm:
    name: "{{ infra_workflow_namespace }}-events"
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    chart_ref: argo/argo-events
    release_namespace: "{{ infra_workflow_namespace }}"
    create_namespace: True
    purge: True
    force: True
    wait: True
    replace: True
    update_repo_cache: True
    values:
      openshift: true

- name: Create EventBus and ServiceAccount
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_workflow_namespace }}"
    state: present
    verify_ssl: no
    src: "{{ item }}"
    apply: true
  with_fileglob: 'templates/argo-workflows/install/*'

- name: Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5
  when: argo_app.changed

- name: Wait for EventBus creation
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    kind: EventBus
    api_version: argoproj.io/v1alpha1
    name: skodjob
    wait: true
    verify_ssl: no
    wait_condition:
      type: Deployed
      status: True
      reason: Succeeded
