---
- include_tasks:
    file: cluster-logging/install_loki_stack.yaml
  loop: "{{ clusters }}"
  loop_control:
    loop_var: clusterName
  vars:
    logging_loki_s3_secret: logging-loki-s3

- include_tasks:
    file: cluster-logging/install_cluster_logging.yaml
  loop: "{{ clusters }}"
  loop_control:
    loop_var: clusterName

- include_tasks:
    file: cluster-logging/setup_datasources.yaml
  loop: "{{ clusters_dict.values() }}"
  loop_control:
    loop_var: cluster
