- name: Deploy chaos engineering resources for Tekton from Jinja2 templates
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    template: "{{ item }}"
    verify_ssl: no
    apply: true
  with_fileglob: 'templates/tekton/pipelines/chaos/*.j2'

- name: Deploy non-template chaos engineering cron-jobs for Tekton
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    template: "{{ item }}"
    verify_ssl: no
    apply: true
  with_fileglob: 'templates/tekton/pipelines/chaos/cron-jobs/*.yaml'
