---
- name: Create Strimzi related Tekton pipelines
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    template: "{{ item }}"
    verify_ssl: no
    apply: true
  with_fileglob: 'templates/tekton/pipelines/strimzi-deployment/*.yaml*'

- name: Sleep for 5 seconds and continue with play (wait tull everything is setup)
  wait_for:
    timeout: 5

- name: Create Strimzi related Tekton pipeline runs
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    verify_ssl: no
    apply: true
    template: "templates/tekton/pipelines/strimzi-deployment/run/pipeline-runs.yaml"
