name: tealc-ee

on:
  push:
    branches:
      - "main"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./tealc-ee/context
          file: ./tealc-ee/context/Dockerfile
          push: true
          tags: quay.io/tealc/tealc-ee:latest
